def transliteration(text: str):
    return text.replace("іє", 'ie') \
        .replace("Іє", 'Ie') \
        .replace("ія", 'ia') \
        .replace("Ія", 'Ia') \
        .replace("зг", 'zgh') \
        .replace("Зг", 'Zgh') \
        .replace("ьо", 'io') \
        .replace("а", 'a') \
        .replace("б", 'b') \
        .replace("в", 'v') \
        .replace("г", 'h') \
        .replace("ґ", 'g') \
        .replace("д", 'd') \
        .replace("е", 'e') \
        .replace("є", 'ie') \
        .replace("ж", 'zh') \
        .replace("з", 'z') \
        .replace("и", 'y') \
        .replace("і", 'i') \
        .replace("ї", 'i') \
        .replace("й", 'i') \
        .replace("к", 'k') \
        .replace("л", 'l') \
        .replace("м", 'm') \
        .replace("н", 'n') \
        .replace("о", 'o') \
        .replace("п", 'p') \
        .replace("р", 'r') \
        .replace("с", 's') \
        .replace("т", 't') \
        .replace("у", 'u') \
        .replace("ф", 'f') \
        .replace("х", 'kh') \
        .replace("ц", 'ts') \
        .replace("ч", 'ch') \
        .replace("ш", 'sh') \
        .replace("щ", 'sch') \
        .replace("ь", '') \
        .replace("ю", 'iu') \
        .replace("я", 'ia') \
        .replace("А", 'A') \
        .replace("Б", 'B') \
        .replace("В", 'V') \
        .replace("Г", 'H') \
        .replace("Ґ", 'G') \
        .replace("Д", 'D') \
        .replace("Е", 'E') \
        .replace("Є", 'Ie') \
        .replace("Ж", 'Zh') \
        .replace("З", 'Z') \
        .replace("И", 'Y') \
        .replace("І", 'I') \
        .replace("Ї", 'I') \
        .replace("Й", 'I') \
        .replace("К", 'K') \
        .replace("Л", 'L') \
        .replace("М", 'M') \
        .replace("Н", 'N') \
        .replace("О", 'O') \
        .replace("П", 'P') \
        .replace("Р", 'R') \
        .replace("С", 'S') \
        .replace("Т", 'T') \
        .replace("У", 'U') \
        .replace("Ф", 'F') \
        .replace("Х", 'Kh') \
        .replace("Ц", 'Ts') \
        .replace("Ч", 'Ch') \
        .replace("Ш", 'Sh') \
        .replace("Щ", 'Sch') \
        .replace("Ь", '') \
        .replace("Ю", 'Iu') \
        .replace("Я", 'Ia')


if __name__ == '__main__':
    print(translit("Ірпінь"))
